- package.json
> Add react, react-dom v17 to peer dependency

- build/index.es.js
- demo/package-lock.json
- demo/package.json
- demo/src/App.js
- package-lock.json
- package.json
- src/index.tsx
- issue에 있는 해결책 보고, 똑같이 설정해두었습니다.
- 또한, hook 사용 잘되는 것 확인하였습니다.
> demo app react module path 수정

- package.json
package.json에 types property를 추가했습니다.
- 참고문서: [TypeScript:Documentation - Publishing](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html)
resolve #20
> npm 패키지에 타입 선언 추가

- demo/src/index.tsx
- src/__tests__/component.spec.tsx
- src/components/AnalyticsProvider/index.tsx
- src/contexts/AnalyticsProviderContext.ts
- src/index.tsx
- src/utils/googleAnalytics/initialize.ts
- setting한 prettier, eslint rule에 맞게 기존 코드 fix
(도움이 필요한 부분들을 적어주세요.)
resolve #
fix #
- [ x] 모든 **변경점**들을 확인했으며 적절히 설명했습니다..
- [ x] 빌드와 테스트가 정상적으로 수행됨을 확인했습니다. (`npm run build`, `npm run test`)
> 기존 코드 formatting

- demo/src/components/NavBar.tsx
- demo/src/index.tsx
- demo/src/pages/MainPage/index.tsx
- demo/src/pages/ProductsPage/index.tsx
- demo/src/utils/fruitLogger/index.ts
- demo/src/utils/location.ts
- src/components/AnalyticsProvider/index.tsx
- src/contexts/AnalyticsProviderContext.ts
- src/contexts/useAnalyticsContext.ts
- src/index.tsx
- src/utils/googleAnalytics/index.ts
- src/utils/googleAnalytics/initialize.ts
https://github.com/EveryAnalytics/react-analytics-provider/issues/30
에 디테일한 Before/After코드, 리팩토링 이유를 적었습니다
resolve #
fix #
> #30 AnalyticsProvider를 context api기반으로 리팩터링, PageView이벤트 추가

- src/__tests__/component.spec.tsx
- src/components/Sample.tsx
- src/index.tsx
- src/utils/googleAnalytics/event.ts
- src/utils/googleAnalytics/index.ts
- src/utils/googleAnalytics/initialize.ts
더러운 코드를 정리합니다
(도움이 필요한 부분들을 적어주세요.)
resolve #
fix #
> chore: 라이브 코딩 전에 코드 정리

- src/utils/googleAnalytics/index.ts
- src/utils/googleAnalytics/set.ts
gtag의 set을 호출하는 함수입니다. [API 레퍼런스 링크](https://developers.google.com/gtagjs/reference/api#set)
(도움이 필요한 부분들을 적어주세요.)
resolve #47 
> googleAnalytics.set 추가

- LICENSE
~라이센스 파일을 추가했습니다. [아파치 2.0](https://www.olis.or.kr/license/Detailselect.do?lId=1002)을 선택했습니다.~
**수정** MIT로 변경했습니다!
[FreeBSD](https://www.olis.or.kr/license/Detailselect.do?lId=1093&mapCode=010003&lType=osi), [MIT](https://www.olis.or.kr/license/Detailselect.do?lId=1006&mapCode=010006&lType=osi)도 고려해봤는데 아파치 2.0이 제일 무난한 것 같아 선택했습니다! (큰 이유는 없습니다 😅 )
혹시 좋은 의견 있으시면 댓글 부탁드립니다 ㅎㅎ
resolve #2 
fix #
> LICENSE 추가 (MIT)

- demo/README.md
- demo/with-cra/src/App.tsx
- demo/with-cra/src/router/Route.tsx
demo/with-cra 에서 npm start를 하면 src/App.tsx와 src/router/Route.tsx 에서 prettier/prettier 에러가 발생하였습니다.
`npx eslint src/App.tsx --fix`
`npx eslint src/router/Route.tsx --fix`
를 해주니 해결되었습니다.
(도움주신 분들 모두 감사합니다 😭🙏🏻 덕분에 eslint와 prettier에 대해 좀더 알아가게 되었슴다,,,👍🏻)
그런데 에러는 아니지만 경고가 뜨긴 하네요
resolve #82, 80
fix #82, 80
> Fix format error (eslint fix)

- .all-contributorsrc
- README.md
1. README의 내용을 보강하고 좀 더 꾸몄습니다. 개발 관련된 내용은 모두 contributing.md로 옮겼습니다. (참고한 문서들: [next.js](https://github.com/vercel/next.js/blob/canary/packages/next/README.md), [styled-components](https://github.com/styled-components/styled-components/blob/main/README.md), [dayjs](https://github.com/iamkun/dayjs/blob/dev/README.md))
2. Contributors 구현을 위해 [All Contributors](https://allcontributors.org/docs/en/overview)를 도입했습니다!
변경 결과는 [여기](https://github.com/greatSumini/react-analytics-provider/blob/docs/59/enrich-readme/README.md)에서 확인하실 수 있습니다 
@milooy All Contributors GitHub App 설치 Request 승인 부탁드려유~!
resolve #59
> README 꾸미기

- README.md
#95 에서 실수가 있었네요.. README에 All Contributors 관련 코드가 있어야지만 정상적으로 추가된다고 합니다 ㅎ.ㅠ
정상적으로 작동하는지 테스트해보지 않은 제 불찰입니다 😭 
이번에는 모든 작동 확인했습니다~
이렇게 이슈에서 댓글을 달면
이렇게 PR이 생성되고,
머지하면 이렇게 컨트리뷰터가 추가됩니다!
> README에 all-contributors table 코드 추가

- demo/with-nextjs/package.json
- demo/with-nextjs/yarn.lock
- nextjs demo app module path 수정하였습니다.
resolve #
fix #
> module path 수정

- .github/workflows/ci.yml
- package.json
1. type-check script를 추가했습니다.
2. CI 워크플로우에 type-check script를 호출하는 step을 추가했습니다!
**CI 수행 테스트 결과 - 정상 😃**
**타입 오류 테스트 결과 - 정상 🥳**
resolve #114 
fix #
> ci: CI 워크플로우에 Type check 추가

- src/hooks/useAnalyticsPageView.ts
`Record<string, unknown>` 이 `UnknownRecord` 타입과 중복되므로 `UnknownRecord` 타입을 적용시켰습니다.
resolve #
fix #
> Apply UnknownRecord Type

- jest.config.js
- package-lock.json
- package.json
#149 를 먼저 한번에 열었다가, 패키지 설치 및 환경 설정을 코드 수정과 함께 묶는 것은 아무래도 좀.. 아닌 것 같아 따로 PR 열었습니다!
이 PR에 포함된 작업은 다음과 같습니다.
1. 테스트 중 사용할 더미데이터 생성을 위해 [faker](https://github.com/marak/Faker.js/) 패키지를 설치했습니다.
2. jest, ts-jest를 최신 버전으로 업데이트했습니다. (^27.1.0, ^27.0.5)
3. window, document에 접근하는 일이 많아 jest testEnvironment를 'jsdom'으로 설정했습니다. 
추후에 있을 React Component 테스팅에도 필요합니다 😄 
faker는 `faker.datatype.number`, `faker.phone.phoneNumber` 등 여러 더미데이터 생성 함수를 제공해주는 라이브러리입니다!
사실 막 엄청 필수적이진 않은데.. 삭제하는게 나을까요? 전 정말 좋아하긴 하는데 ㅎㅎ
> test: 테스트 패키지 설치, 환경 변경

- .github/pull_request_template.md
- .github/workflows/ci.yml
- .github/workflows/lint-pr.yml
PR template 타이틀을 검사하는 
https://github.com/marketplace/actions/semantic-pull-request 
워크플로우를 추가했습니다.
그리고 PR template에 관련 내용을 적었습니다~
resolve #115
fix #
> ci: semantic-pull-request 워크플로우 추가,  PR template에 관련 내용 추가

- demo/with-cra/src/index.tsx
- package-lock.json
- package.json
- src/utils/amplitude/index.ts
- src/utils/amplitude/initialize.ts
- src/utils/amplitude/logEvent.ts
- src/utils/index.ts
- 별도로 instance 함수를 실행하지 않고 함수를 사용할 수 있도록 util 함수를 만들었습니다. 
- 위 컨셉이 괜찮은지 확인해보고, 나머지 더 필요한 유틸들을 추가할 예정입니다. 
- amplitude-js 의 dependecy를 peerDependency로 해야하는지, 잘 모르겠습니다. 
resolve #105
> feat: amplitude util 함수 

- src/utils/googleAnalytics/initialize.ts
* window.dataLayer operator 변경 (Logical OR => Nullish coalescing)
* relates to #168
window.dataLayer 할당에 사용되는 연산자 변경
* 기존 falsy 한 값인지를 체크하는 것에서 명확히 undefined 또는 null인지를 체크하는 것으로 변경하여 의도치 않은 버그 발생 확률 감소
* Logical OR => Nullish coalescing
resolve #168
fix #
> refactor: Update window.dataLayer operator

- demo/with-cra/src/index.tsx
- src/utils/googleAnalytics/index.ts
- tests/utils/googleAnalytics/click.test.ts
- tests/utils/googleAnalytics/initialize.test.ts
논의 링크: https://github.com/EveryAnalytics/react-analytics-provider/pull/117#discussion_r696773527
amplitudeHelper와 통일을 위해 googleAnalyticsHelper로 변경했습니다.
resolve #172
fix #
> refactor: rename googleAnalytics -> googleAnalyticsHelper

- .github/pull_request_template.md
PR 템플릿의 `npm run build`, `npm run test`를 `yarn build`, `yarn test`로 변경했습니다.
resolve #
fix #
> docs: replace npm scripts to yarn (in PR template)

- tests/utils/googleAnalytics/event.test.ts
테스트코드를 공부하고 작성을 진행했습니다.
event의 파라미터에 따른 테스트를 진행했습니다.
[테스트 셋업 길드] 테스트 디렉토리 구조, 어떻게 잡는게 좋을까요? #132
[테스트 셋업 길드]AnalyticsProviderContext 테스트 코드 관련해서 여쭤보고싶어요 ~! #128
[테스트 셋업 길드] Add googleAnalytics.click test code PR #167  
[테스트 셋업 길드] googleAnalytics.initialize 테스트 추가 PR #149 
파라미터 정의를 이런식으로 진행했습니다. 고민이 많았습니다. faker를 사용해서 만들어보고 싶어서요ㅠ
```
const params = {foo: 'bar'}; // <=로 사용   
// const params = {[`${faker.lorem.word()}`] : faker.lorem.word()} 
// << 이런식으로 쓸까했다가 성철님의 코드를 보고 위처럼 사용했습니다.
```
그래서 faker에 어떤것들이 있나 살펴보았습니다.
저희는 다른부분도 좋지만 나중에 커머스관련 Event를 진행할때 product 부분에서 facker가 유용할게 사용될 것으로 보입니다!
resolve #137 
fix #
> test: googleAnalytics.event테스트 코드 작성

- tests/utils/googleAnalytics/event.test.ts
event test code에 global 키워드로 인한 버그 발생 해결
resolve #
fix #137
> fix: "test: googleAnalytics.event테스트 코드 작성" global 사용으로 인한 CI 오류 발생

- package.json
- tests/utils/googleAnalytics/amplitude/initialize.test.ts
- amplitudeHelper.initialize test를 추가합니다. 
- package.json script 에 test:watch 를 추가합니다. (test 작성할 때 watch 하면서 코드 변화 있을 때마다 run 해주는 역할) 
resolve #182
fix #
> test: amplituedeHelper.initialize

- src/utils/amplitude/index.ts
- src/utils/amplitude/logRevenueV2.ts
- tests/utils/amplitude/logRevenueV2.test.ts
amplitude javascript sdk의 logRevenueV2를 wrapping하는 함수입니다.
1. amplitudeHelper.logRevenueV2를 추가했습니다.
2. Revenue class도 함깨 export했습니다.
3. 추가된 logRevenueV2의 테스트를 작성했습니다.
**참고 자료**
- [amplitude Javascript SDK - Track Revenue](https://developers.amplitude.com/docs/javascript#track-revenue)
- [amplitude문서 - Tracking Revenue](https://help.amplitude.com/hc/en-us/articles/115003116888)
resolve #193
fix #
> feat: add amplitudeHelper.Revenue, logRevenueV2

- tests/utils/amplitude/initialize.test.ts
- tests/utils/amplitude/logEvent.test.ts
- amplitudeHelper.logEvent 의 test 함수를 작성했습니다. 
- https://github.com/EveryAnalytics/react-analytics-provider/pulls?q=is%3Apr+is%3Aclosed 에서 folder path를 잘못 설정해서 수정하였습니다. 
resolve #183 
fix #
> test: amplitudeHelper.logEvent

- CONTRIBUTING.md
- package.json
1. Published v0.2.0 to https://www.npmjs.com/package/@every-analytics/react-analytics-provider
2. Add npm module publishing guide to CONTRIBUTING.md
브랜치전략은 추후 논의해봐요!
resolve #
fix #
> feat: NPM module version up - 0.2.0, Add guide to CONTRIBUTING.md

- src/utils/amplitude/index.ts
- src/utils/amplitude/setUserProperties.ts
- tests/utils/amplitude/setUserProperties.test.ts
- tests/utils/googleAnalytics/event.test.ts
Amplitude setUserProperties 를 추가했습니다.
Amplitude setUserProperties Test를 추가했습니다.
setUserProperties에 빈객체를 넘겨주었을 경우를 Test를 진행했습니다.
setUserProperties를 하는데 빈객체를 넣어주면 warning을 하도록했습니다.
이부분을 더 명확하게하는 방법이 있을까요? 그리고 진행하지 않아도 되는 오버스팩일까요?
resolve #199
resolve #200 
fix #
> feat: Amplitude setUserProperties 추가 & test: Amplitude setUserProperties

- .npmignore
- package.json
* update license type
* relates to #208
* `package.json`  license is modified to change license type
* `ISC` => `MIT`
fix #208
> fix: Update package.json to change license type

- demo/with-cra/src/App.tsx
- demo/with-cra/src/pages/CartPage/index.tsx
CartPage를 만들고 router 설정을 한 간단한 PR입니다.
이후 
- component 만들기
- context 작성
- 장바구니 추가로직
- onClick 구현
진행할 계획입니다!
resolve #244
fix #
> feat: add demo cart page

- demo/with-cra/src/App.tsx
- demo/with-cra/src/contexts/MainContext.tsx
- demo/with-cra/src/contexts/index.tsx
- demo에 사용되는 context api 작성
```tsx
user: User;
setUser(user: User): void;
cartItems: ProductItem[];
setCartItem(cartItem: ProductItem[]): void;
purchaseItems: ProductItem[];
setPurchaseItems(purchaseItems: ProductItem[]): void;
```
fair programming with @uoon-dev @Leehaeun0 
resolve #257
fix #
> feat: implement context api
